title: <p align="center"> Ferry Ath Thaariq Mudhofir </p>

logo: "/images/Profile Kalibrasi - Circle.png?raw=true"

description:
  <p align="center">
  <a href="https://intip.in/CVDataAnalystFerryATM">Resume</a> |
  <a href="https://www.linkedin.com/in/ferry-ath-thaariq-mudhofir/">LinkedIn</a> |
  <a href="https://github.com/ferryatm/">GitHub</a>
  </p>
  
  <p align="justify">
  A dedicated junior geophysicist and data enthusiast with hands-on experience in subsurface exploration and data-driven decision-making. Keen to contribute to innovative projects that foster creativity.
  <br><br>

  <p align="center">
  "Numbers have important stories to tell, data will speak if you’re willing to listen."
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID 
