title: <p align="center"> Ferry Ath Thaariq Mudhofir </p>

logo: "/images/picture-cicle.png?raw=true"

description:
  <p align="center">
  <a href="https://intip.in/cvferry">Resume</a> |
  <a href="https://www.linkedin.com/in/ferry-ath-thaariq-mudhofir/">LinkedIn</a> |
  <a href="https://github.com/ferryatm/">GitHub</a>
  </p>
  
  <p align="justify">
  I am Physics Student at Faculty of Science and Data Analytics, Sepuluh Nopember Institute of Technology.
  <br><br>
  An individual with excellent interpersonal and intrapersonal skills, making it effortless to socialize with others. Able to analyze data and understand programming languages such as Python and C/C++, as evidenced by completing >5 projects..
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
