title: <p align="center"> Ferry Ath Thaariq Mudhofir </p>

logo: "/images/picture-cicle.png?raw=true"

description:
  <p align="center">
  <a href="https://intip.in/CVDataAnalystFerryATM">Resume</a> |
  <a href="https://www.linkedin.com/in/ferry-ath-thaariq-mudhofir/">LinkedIn</a> |
  <a href="https://github.com/ferryatm/">GitHub</a>
  </p>
  
  <p align="justify">
  Junior data analyst with sufficient in Python and SQL for data cleaning, manipulation, analysis, and interpretation. Capable of analyzing problems with a logical approach and articulating the complexity of data through easily understandable visualizations.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID 
